### ISSUE TITLE
[Bug] Duplicate category names causes bot start to fail

### ISSUE THREAD

**Issue by TheColorman** [thomst08/requestrr#17]
See [this](https://github.com/thomst08/requestrr/issues/17#issuecomment-1987020002) comment for the diagnosed problem:
> Issue stemmed from having multiple categories with the same name across Radarr and Sonarr. Making sure no category name was repeated twice fixed the issue (e.g. don't have an `anime` category in both the Radarr and Sonarr configs).

Original post:
---

When I start the bot (running in a Docker container) I get the following error:
```log
requestrr  | [2024-02-29 12:46:30 +00:00] [0   /            ] [Crit ] There was an error registering application commands: Invalid Form Body
requestrr  | DSharpPlus.Exceptions.BadRequestException: Bad request: 400
requestrr  |    at DSharpPlus.Net.DiscordApiClient.BulkOverwriteGuildApplicationCommandsAsync(UInt64 application_id, UInt64 guild_id, IEnumerable`1 commands)
requestrr  |    at DSharpPlus.SlashCommands.SlashCommandsExtension.<>c__DisplayClass39_0.<<RegisterCommands>b__0>d.MoveNext()
```

It *has* registered slash commands (probably from first boot?), but using any of them results in "The application did not respond", with no activity in the logs.

Only network settings I have set up is that DNS is routed through Pihole, running in an adjacent container. None of my other container have network connectivity problems with my routing setup.
docker-compose.yaml:
```yaml
version: "3.4"
services:
  requestrr:
    image: thomst08/requestrr
    hostname: requestrr
    container_name: requestrr
    ports:
    - 4545:4545
    volumes:
    - ./config:/root/config
    restart: unless-stopped
    dns:
      - 192.168.50.58 # private IP of the raspberry pi hosting both Pihole and requestrr. I also use this setup in other containers.
```

I have no custom language files. This is from a clean install right after setting up Radarr and Sonarr connections.

Running requestrr 2.1.5

**Comment by thomst08** [comment]
Hey @TheColorman,
Sorry for the late reply on this issue, I believe this might be linked to the issue #9, but I will test it to find out.
Thank you for the detailed information, that gives me something to work with.
I will let you know when I have something.

**Comment by TheColorman** [comment]
Tried to debug a bit on Windows on a dev server, but no I'm not seeing the issue...

**Comment by TheColorman** [comment]
_also_ don't get the error when starting a container with the exact same compose.yaml on my dev pc. Could it have something to do with the arm architecture?

**Comment by TheColorman** [comment]
Tried to build it in a container:
`Dockerfile`
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine

RUN apk add --no-cache \
    git \
    npm

RUN git clone https://github.com/thomst08/requestrr.git /app

WORKDIR /app/Requestrr.WebApi/ClientApp

RUN npm install
RUN npm run build

WORKDIR /app/Requestrr.WebApi

RUN dotnet publish -c release -o publish

WORKDIR /app/Requestrr.WebApi/publish

ENTRYPOINT [ "dotnet", "Requestrr.WebApi.dll" ]
```
`compose.yaml`
```yaml
version: "3.4"
services:
  requestrr:
    build: .
    hostname: requestrr
    container_name: requestrr
    ports:
    - 4545:4545
    volumes:
    - ./config:/app/Requestrr.WebApi/publish/config
    restart: unless-stopped
```

Again, worked just fine on my PC, but I get the application command error on my raspberry pi.
